name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push first Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./servers
        file: ./servers/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/abohmeed/server-nestjs-image:latest
          ghcr.io/${{ github.repository_owner }}/abohmeed/server-nestjs-image:${{ github.sha }}

    - name: Build and push second Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./clients/user-service-ui
        file: ./clients/user-service-ui/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/ui-next-image:latest
          ghcr.io/${{ github.repository_owner }}/ui-next-image:${{ github.sha }}
